const locale = {
  startsWith: "Начинается с",
  contains: "Содержит",
  notContains: "Не содержит",
  endsWith: "Заканчивается на",
  equals: "Равно",
  notEquals: "Не равно",
  noFilter: "No Filter",
  lt: "Меньше чем",
  lte: "Меньше или равно чем",
  gt: "Больше чем",
  gte: "Больше или равно чем",
  dateIs: "Date is",
  dateIsNot: "Date is not",
  dateBefore: "Date is before",
  dateAfter: "Date is after",
  clear: "Отчистить",
  apply: "Применить",
  matchAll: "Все",
  matchAny: "Любой",
  addRule: "Добавить правило",
  removeRule: "Удалить правило",
  accept: "Да",
  reject: "Нет",
  choose: "Выбрать",
  upload: "Загрузить",
  cancel: "Отмена",
  dayNames: [
    "Воскресенье",
    "Понедельник",
    "Вторник",
    "Среда",
    "Четверг",
    "Пятница",
    "Суббота",
  ],
  dayNamesShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Сбт"],
  dayNamesMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  monthNames: [
    "Январь",
    "Февраль",
    "Март",
    "Апрель",
    "Май",
    "Июнь",
    "Июль",
    "Август",
    "Сентябрь",
    "Октябрь",
    "Ноябрь",
    "Декабрь",
  ],
  monthNamesShort: [
    "Янв",
    "Фев",
    "Мар",
    "Апр",
    "Май",
    "Июн",
    "Июл",
    "Авг",
    "Сен",
    "Окт",
    "Ноя",
    "Дек",
  ],
  chooseYear: "Выберите Год",
  chooseMonth: "Выберите Месяц",
  chooseDate: "Выберите Дату",
  prevDecade: "Выберите Десятилетие",
  nextDecade: "Следующее Десятилетие",
  prevYear: "Предыдущий Год",
  nextYear: "Следующий Год",
  prevMonth: "Предыдущий Месяц",
  nextMonth: "Следующий Месяц",
  prevHour: "Предыдущий Час",
  nextHour: "Следующий Час",
  prevMinute: "Предыдущая Минута",
  nextMinute: "Следующая Минута",
  prevSecond: "Предыдущая Секунда",
  nextSecond: "Следующая Секунда",
  am: "am",
  pm: "pm",
  today: "Сегодня",
  weekHeader: "Неделя",
  firstDayOfWeek: 1,
  dateFormat: "dd.mm.yy",
  weak: "Слабый",
  medium: "Средний",
  strong: "Сложный",
  passwordPrompt: "Введите пароль",
  emptyFilterMessage: "Не найдено", // @deprecated Use 'emptySearchMessage' option instead.
  searchMessage: "Доступно {0} элементов",
  selectionMessage: "{0} элементов выбрано",
  emptySelectionMessage: "Не выбрано",
  emptySearchMessage: "Не найдено",
  emptyMessage: "Нет доступных элементов",
  aria: {
    trueLabel: "Истина",
    falseLabel: "Ложь",
    nullLabel: "Не выбрано",
    star: "1 звезда",
    stars: "{star} звезд",
    selectAll: "Все элементы выбраны",
    unselectAll: "Элементы не выбраны",
    close: "Закрыть",
    pageLabel: "Страница",
  },
};

export default locale;
